<?xml version="1.0" encoding="windows-1250"?>
<?xml-stylesheet href="project.xsl" type="text/xsl"?>
<!DOCTYPE project [
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT copyright (#PCDATA)>
  <!ELEMENT licence (#PCDATA)>
  <!ELEMENT update (date, version, point+)>
  <!ELEMENT feature (point+)>
  <!ELEMENT date  (#PCDATA)>
  <!ELEMENT version (#PCDATA)>
  <!ELEMENT point (#PCDATA)>
]>

<project>
  <name>Modbus Configurator</name>
  <description>Software, kterı je urèenı k pøepínání typu komunikaèního protokolu našich zaøízení, hlavnì mezi Spinelem a MODBUSem RTU. Kromì pøepínání protokolù program umí také vyhledávat a nastavovat komunikaèní parametry zaøízení.</description>
  <copyright>Papouch s.r.o.</copyright>

  <update>
    <date>4.2.2019</date>
    <version>1.0.7.0</version>
    <point>Oprava komunikace, zmìna poøadí jnavazování spojení pøi vyhledávání modulu.</point>	
  </update>

  <update>
    <date>8.3.2016</date>
    <version>1.0.4.1</version>
    <point>Pøidána tajná skrytá funkce :)</point>	
  </update>
  
  <update>
    <date>23.2.2012</date>
    <version>1.0.4.0</version>
    <point>U spojení s malımi pøenosovımi rychlostmi byla prodlouena doba èekání na odpovìï dotazu.</point>	
    <point>Pøibyla monost zakázat zjišování zaøízení pøes univerzální adresu.</point>	
    <point>Opravena chyba u navazování TCP spojení.</point>	
  </update>

  <update>
    <date>13.10.2011</date>
    <version>1.0.3.1</version>
    <point>Some bug fixed.</point>	
  </update>
  
  <update>
    <date>20.1.2011</date>
    <version>1.0.3.0</version>
    <point>Do programu pøibyla jazyková podpora (èeština, angliètina).</point>
  </update>
  
  <update>
    <date>9.12.2010</date>
    <version>1.0.2.0</version>
    <point>V dialogu "Nastavení pøipojení" pøibyla monost pøipojení pøes TCP.</point>
    <point>Pøibyla funkce vyhledání zaøízení.</point>
  </update>

  <update>
    <date>2.12.2010</date>
    <version>1.0.1.0</version>
    <point>V dialogu "Nastavení pøipojení" pøibylo pole pro urèení adresy zaøízení.</point>
	<point>Nastavení komunikaèních parametrù je novì moné pouze v reimu "Expert mode".</point>
	<point>Pokud je bìhem ukládání parametrù zaøízení pøepnuto do jiného protokolu, pak	se parametry znova uloí pøes novı protokol.</point>
  </update>

</project>