<?xml version="1.0" encoding="windows-1250"?>
<?xml-stylesheet href="project.xsl" type="text/xsl"?>
<!DOCTYPE project [
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT copyright (#PCDATA)>
  <!ELEMENT licence (#PCDATA)>
  <!ELEMENT update (date, version, point+)>
  <!ELEMENT feature (point+)>
  <!ELEMENT date  (#PCDATA)>
  <!ELEMENT version (#PCDATA)>
  <!ELEMENT point (#PCDATA)>
]>

<project>
  <name>Wix</name>
  <description>SW pro mìøení a vizualizaci namìøenıch dat</description>
  <copyright>Papouch s.r.o.</copyright>

  <update>
    <date>29.5.2019</date>
    <version>1.9.0.4</version>
    <point>Watmetr METRA MPG96 - pøidány zobrazované hodnoty</point>

  </update>

  <update>
    <date>19.3.2019</date>
    <version>1.9.0.3</version>
    <point>Pøidán Watmetr METRA MPG96</point>

  </update>

  <update>
    <date>9.1.2019</date>
    <version>1.9.0.2</version>
    <point>Opraveno zobrazení a nastavení zapnutí kontaktu na urèitou dobu.</point>
    <point>Pøidáno zaøízení Netio power cable.</point>

  </update>

  <update>
    <date>6.12.2018</date>
    <version>1.9.0.1</version>
    <point>Opraveno ètení vstupu u zaøízení Modbux RTU/TCP (èetla se jedna hodnoéta navíc).</point>

  </update>

  <update>
    <date>1.12.2018</date>
    <version>1.9.0.0</version>
    <point>Opraven posun akce nahoru dolù.</point>
    <point>Rozšíøené nastavení pøepoètu.</point>    
    <point>Modbus zaøízení mohou nastavovat vıstupy.</point>    
    <point>Pøidány moduly ADAM 6217,6060,6051,6050,6024,6022,6018,6017,4022,4015,4015T,4150, (komunikace modbus).</point>
    <point>Mono  pøipojit plugin pro export dat (v souèasnosti do databáze).</point>
    <point>Pøidán wix.ini pro konfiguraci Wixu.</point>
    <point></point>
  </update>


  <update>
    <date>31.8.2018</date>
    <version>1.8.9.3</version>
    <point>Pøidáno Quido 4/32 OC a TQS4</point>
    <point>AD4 - Zobrazení bipolárních hodnot</point>
    <point>Pøidáno XML pro PAPAGO 2TH,2TC,2PT</point>
    <point>Opraven export dlouhıch xml a csv dat, pøes webovı server (a 1 000 000 øádkù csv a 10 000 øádkù xml).</point>
  </update>

  <update>
    <date>17.7.2018</date>
    <version>1.8.9.2</version>
    <point>Úpravy pro pouívání doplòku Quido Èasovaè</point>
  </update>

  <update>
    <date>17.7.2018</date>
    <version>1.8.9.1</version>
    <point>Pøeklad smìrù vìtru (TC20) do angliètiny</point>
  </update>

  <update>
    <date>28.6.2018</date>
    <version>1.8.9.0</version>
    <point>Podpora zaøízení modbus TCP/IP</point>
    <point>Modbus je schomen èíst binární hodnoty (cívky, diskrétní vstupy)</point>
    <point>Pøidány moduly ADAM 6050,6217,4150,4015T a WISE 4012E (komunikace modbus)</point>    
  </update>

  <update>
    <date>13.9.2017</date>
    <version>1.8.8.5</version>
    <point>Opravena kontrola data a èasu ve webovém rozhraní</point>
  </update>

  <update>
    <date>22.2.2017</date>
    <version>1.8.8.4</version>
    <point>Pøidán elektromìr PRO1-Mod.</point>
  </update>
  
  <update>
    <date>15.2.2017</date>
    <version>1.8.8.3</version>
    <point>Pøidán modul Quido RS 10/16 OC.</point>
  </update>
  
  <update>
    <date>23.12.2016</date>
    <version>1.8.8.2</version>
    <point>Pøidána monost vlastního uspoøádání akcí.</point>
  </update>
  
  <update>
    <date>10.11.2016</date>
    <version>1.8.8.1</version>
    <point>Pøidán protokol HTTPS.</point>
  </update>
  
  <update>
    <date>19.10.2016</date>
    <version>1.8.8.0</version>
    <point>Pøidán modul TDS-101 ETH.</point>
    <point>Akce "Poslat SMS" rozšíøena o modemy EGS5-T, BGS5-232 a BGS3-TUB.</point>
  </update>

  <update>
    <date>25.8.2016</date>
    <version>1.8.7.2</version>
    <point>Nìkteré chyby opraveny.</point>
  </update>

  <update>
    <date>20.7.2016</date>
    <version>1.8.7.1</version>
    <point>Pøidán modul Papago TH 2DI DO.</point>
  </update>

  <update>
    <date>14.4.2016</date>
    <version>1.8.7.0</version>
    <point>Pøidán displej TDS-57.</point>
    <point>Pøidána monost pøesouvat panılky taením myši (pøes CTRL).</point>
  </update>
  
  <update>
    <date>8.4.2016</date>
    <version>1.8.6.8</version>
    <point>Nìkteré chyby opraveny.</point>
  </update>
  
  <update>
    <date>16.3.2016</date>
    <version>1.8.6.7</version>
    <point>Nìkteré chyby opraveny.</point>
  </update>
  
  <update>
    <date>8.3.2016</date>
    <version>1.8.6.6</version>
    <point>Nìkteré chyby opraveny.</point>
  </update>

  <update>
    <date>2.3.2016</date>
    <version>1.8.6.5</version>
    <point>Pøidán protokol Drak4.</point>
  </update>

  <update>
    <date>26.2.2016</date>
    <version>1.8.6.4</version>
    <point>Vytvoøená light varianta u elektromìru DVH5261.</point>
    <point>Pøidána jazyková podpora u názvù vstupù.</point>
  </update>
  
  <update>
    <date>26.1.2016</date>
    <version>1.8.6.3</version>
    <point>Nìkteré chyby opraveny.</point>
  </update>
  
  <update>
    <date>14.1.2016</date>
    <version>1.8.6.2</version>
    <point>Pøidán elektromìr DVH5261-M.</point>
    <point>Ve webovém rozhraní se u grafu zobrazuje i popisek.</point>
  </update>

  <update>
    <date>5.1.2016</date>
    <version>1.8.6.1</version>
    <point>Nìkteré chyby opraveny.</point>
  </update>
  
  <update>
    <date>30.11.2015</date>
    <version>1.8.6.0</version>
    <point>Novì je moné sledovat grafy pøes webové rozhraní.</point>
    <point>Pøibyla monost nastavení cesty k souborùm pro grafy.</point>
    <point>V dialogu pro nastavení pøipojení je mono zvolit poèet stopbitù.</point>
  </update>

  <update>
    <date>12.10.2015</date>
    <version>1.8.5.5</version>
    <point>Pøidán modul Papago 5DI 1DO.</point>    
    <point>Opravena chyba vyèítání velièin z THT2 pøes modbus.</point>
  </update>
  
  <update>
    <date>1.9.2015</date>
    <version>1.8.5.4</version>
    <point>Opravena chyba vícenásobného pøístupu k Wixu pøes webové rozhraní.</point>
  </update>
  
  <update>
    <date>11.6.2015</date>
    <version>1.8.5.3</version>    
    <point>Nìkteré chyby opraveny.</point>
  </update>
  
  <update>
    <date>27.3.2015</date>
    <version>1.8.5.2</version>
    <point>Nìkteré chyby opraveny.</point>
  </update>
  
  <update>
    <date>13.3.2015</date>
    <version>1.8.5.1</version>
    <point>Opravena chyba vyèítání zápornıch hodnot z modulu Papago.</point>
  </update>
  
  <update>
    <date>6.2.2015</date>
    <version>1.8.5.0</version>
    <point>Pøidán pomìr zvìtšení panelù Wixu.</point>
  </update>
  
  <update>
    <date>30.1.2015</date>
    <version>1.8.4.0</version>
    <point>Pøidán modul Papago.</point>
  </update>
  
  <update>
    <date>11.12.2014</date>
    <version>1.8.3.2</version>
    <point>Nìkteré chyby opraveny.</point>
  </update>
  
  <update>
    <date>30.10.2014</date>
    <version>1.8.3.1</version>
    <point>V dialogu "Nastavení akcí" pøibyla monost nesynchronizovat spuštìní akcí ke specifickému datu.</point>
    <point>Opravena chyba uloení vıpisu historie z webového rozhraní.</point>
  </update>

  <update>
    <date>15.8.2014</date>
    <version>1.8.3.0</version>
    <point>Pøidáno nastavení barvy panelu v závislosti na hodnotì.</point>
    <point>V grafu pøibyla funkce vyšrafování oblasti pod køivkou.</point>
  </update>
  
  <update>
    <date>20.6.2014</date>
    <version>1.8.2.5</version>
    <point>Aktualizován zpùsob komunikace s novou verzí modulu TME Multi.</point>
  </update>
  
  <update>
    <date>12.6.2014</date>
    <version>1.8.2.4</version>
    <point>Pøidán modul TDS-57.</point>
  </update>
  
  <update>
    <date>13.5.2014</date>
    <version>1.8.2.3</version>
    <point>U akcí novì pøibylo nastavení minimální doby platnosti podmínky pro vyvolání akce.</point>
  </update>
  
  <update>
    <date>7.5.2014</date>
    <version>1.8.2.2</version>
    <point>Pøidán vıpoèet "Digitální hodnota", kterı lze ovládat jak ruènì, tak pomocí akce.</point>
    <point>Pøidána monost vypnutí dialogu informujicí pøekroèení limitu free verze.</point>
  </update>
  
  <update>
   <date>23.4.2014</date>
   <version>1.8.2.1</version>
   <point>Pøidána akce uloit záznam do souboru.</point>
  </update>
  
  <update>
   <date>18.4.2014</date>
   <version>1.8.2.0</version>
   <point>Pøidání zpùsbu komunikace pøes SNMP.</point>
   <point>U Quida komunikující pøes XML pøibyla funkce nulování èítaèù.</point>
   <point>Panılky neaktivních vstupù jsou novì zašedlé.</point>
  </update>

  <update>
   <date>5.3.2014</date>
   <version>1.8.1.3</version>
   <point>Pøidáno zaøízení IncRS.</point>
   <point>Pøidána utilita zobrazující alarmovou zprávu nastavitelného vzhledu (pøes HTML). Lze pouít skrz akci "spustit dávkovı soubor".</point>
   <point>Opravena chyba rovnosti podmínky "vìtší ne".</point>
   <point>Opravena chyba vyèítání historie (pouze hodnoty) pøes webové rozhraní.</point>
  </update>
  
  <update>
   <date>6.1.2014</date>
   <version>1.8.1.2</version>
   <point>Pøidána akce pøehrání zvukového souboru.</point>
  </update>
  
  <update>
   <date>11.11.2013</date>
   <version>1.8.1.1</version>
   <point>Opravena chyba ovládání akcemi relé protokolem XML.</point>
   <point>V nastavení akcí pøibyla monost sychronizovat volání periodickıch akcí s pøesností sekund.</point>
  </update>

  <update>
   <date>24.10.2013</date>
   <version>1.8.1.0</version>
   <point>Pøidány dva vıpoèty "Váenı souèet" a "Váenı souèin".</point>
   <point>Opravena chyba ovládání digitálních vstupù Quida komunikující protokolem XML.</point>
   <point>Opravena chyba ovládání digitálních vstupù Wixu pøes webové rozhraní.</point>
  </update>
  
  <update>
   <date>2.10.2013</date>
   <version>1.8.0.1</version>
   <point>Oravena chyba v akci nastavení analogového vıstupu.</point>
   <point>Oravena chyba ve zkušební akci v dialogu nastavení akcí.</point>
  </update>
  
  <update>
   <date>13.9.2013</date>
   <version>1.8.0.0</version>
   <point>Pøepracování komunikaèního jádra Wixu.</point>
   <point>Pøibyla monost zaheslování nastavení (pouze v plné verzi).</point>
   <point>U nastavení SMTP serveru pøibyla monost nastavit SMTP port.</point>
   <point>Pøidán modul TENZ485.</point>
   <point>Pøidána monost komunikovat se zaøízením THT2 pøes protokol Modbus RTU.</point>
  </update>
  
  <update>
   <date>6.5.2013</date>
   <version>1.7.6.4</version>
   <point>Pøidána podpora podmínek pracující s èasem.</point>
   <point>Odladìno pro systém Windows 2000.</point>   
  </update>
  
  <update>
   <date>16.10.2012</date>
   <version>1.7.6.3</version>
   <point>Pøidána podpora TCP spojení pro zaøízení komunikující pøes modbus RTU.</point>
  </update>
  
  <update>
   <date>2.10.2012</date>
   <version>1.7.6.2</version>
   <point>Opravena chyba nevalidního vstupu pøi pøekroèení hodnoty mimo rozsah.</point>
  </update>
  
  <update>
   <date>14.9.2012</date>
   <version>1.7.6.0</version>
   <point>Pøibyla monost ovládat digitální vıstupy (relé) pøes webové rozhraní.</point>
  </update>
  
  <update>
   <date>3.9.2012</date>
   <version>1.7.5.6</version>
   <point>Pøidáno zaøízení VT 200.</point>
  </update>

  <update>
   <date>29.8.2012</date>
   <version>1.7.5.5</version>
   <point>U webového serveru byla pøidána autorizace.</point>
  </update>
  
  <update>
   <date>7.8.2012</date>
   <version>1.7.5.4</version>
   <point>Opravena chyba mìøení THT2 pøes TME Multi.</point>
  </update>
  
  <update>
   <date>19.7.2012</date>
   <version>1.7.5.3</version>
   <point>Pøidán regulátor teploty E5CN-Q2MT.</point>
  </update>
  
  <update>
   <date>27.6.2012</date>
   <version>1.7.5.2</version>
   <point>Opravena chyba v pøidávání zaøízení TX20-XML.</point>
  </update>
  
  <update>
   <date>24.5.2012</date>
   <version>1.7.5.1</version>
   <point>Pøidána podpora pro èasovì omezené licence.</point>
   <point>Dialog pøidat zaøízení rozdìlen na dva dialogy.</point>
   <point>V prùvodci ukládání pøibyl formát souboru (txt/csv). Pokud je zvolen formát csv, kolem hodnot se vygenerují uvozovky.</point>
   <point>V zaøízení Modbus RTU pøibyl typ hodnoty Signed Int.</point>
   <point>Dialogy nastavení zástupného textu a nastavení bargrafu jsou nyní sizeable.</point>
  </update>
  
  <update>
   <date>7.3.2012</date>
   <version>1.7.5.0</version>
   <point>Pøidán modul eMonica.</point>
   <point>U ruèního ovládání vıstupu Quida (tlaèítka na panelu) lze nastavit sepnutí/rozepnutí relé po urèitou dobu.</point>
   <point>Lze novì ovládat relé modulù Drak4 a Quido-XML prostøednictvím akcí nastavení vıstupu.</point>  
   <point>Pøibyla funkce zálohující konfiguraèní soubory pøi pøechodu na novìjší verzi Wixu.</point>  
  </update>
  
  <update>
   <date>26.1.2012</date>
   <version>1.7.4.0</version>
   <point>Pøibyla monost ètení namìøenıch velièin z Quida pøes XML.</point>
   <point>Pøibyla monost skrıt svislé èáry v grafu (zaèátek a konec mìøení).</point>
  </update>
  
  <update>
   <date>8.12.2011</date>
   <version>1.7.3.1</version>
   <point>Opravena chyba v nastavení podmínky pøekroèení rozsahu.</point>
  </update>
  
  <update>
   <date>1.12.2011</date>
   <version>1.7.3.0</version>
   <point>Pøidána podpora zástupnıch textù do Webu.</point>
   <point>Pøibyla monost volby aktivních vstupù u free verze.</point>
   <point>Poèet aktivních vstupù u free verze novì není omezen, pokud je pøipojeno pouze jedno zaøízení.</point>
  </update>
  
  <update>
   <date>10.11.2011</date>
   <version>1.7.2.0</version>
   <point>Byly pøidány "vıpoètové vstupy" umoòující nastavit vstup jako pøírùstek hodnoty (jiného vstupu) za urèitı èasovı okamik.</point>
  </update>
  
  <update>
   <date>10.10.2011</date>
   <version>1.7.1.0</version>
   <point>U vysokıch dialogù pøibyla monost skrıt hint v záhlaví okna.</point>
   <point>Odstranìní chyby pøetékání èítaèù u Quida.</point>
   <point>Pøibyla monost nastavení èítaèe na konkrétní hodnotu.</point>
   <point>V oknì grafu pod reimem TouchPad pøibyla tlaèítka pro zoom.</point>
  </update>
  
  <update>
   <date>1.8.2011</date>
   <version>1.7.0.9</version>
   <point>V dialogu nastavení pøipojení je nyní tlaèítko pro spuštìní správce zaøízení.</point>
  </update>
  
  <update>
   <date>23.6.2011</date>
   <version>1.7.0.8</version>
   <point>Pøibyla monost nastavení autorizace u dotazování namìøenıch velièin pøes webové rozhraní.</point>
  </update>

  <update>
   <date>30.5.2011</date>
   <version>1.7.0.7</version>
   <point>Upravení nastavení webové stránky u èidla TME-XML.</point>
  </update>
  
  <update>
   <date>26.5.2011</date>
   <version>1.7.0.6</version>
   <point>Pøidán modul TENZ485T.</point>
  </update>
  
  <update>
   <date>31.3.2011</date>
   <version>1.7.0.5</version>
   <point>Pøidána monost rozšíøení DEMO verze na FULL verzi prostøednictvím vloení licenèního souboru do Wixu.</point>
  </update>
  
  <update>
   <date>17.2.2011</date>
   <version>1.7.0.4</version>
   <point>Pøidán modul TENZ485.</point>
   <point>U grafù s velkım èasovım rozpìtím byl prodlouen interval pøekreslování.</point>  
  </update>
  
  <update>
   <date>14.2.2011</date>
   <version>1.7.0.3</version>
   <point>Opravena chyba zamrznutí GUI pøi pøihlášení pøes vzdálenou plochu.</point>   
  </update>
  
  <update>
   <date>20.1.2011</date>
   <version>1.7.0.2</version>
   <point>Opravena chyba ukládání "err" do souboru v dobì, kdy hodnoty byly úspìšnì namìøeny.</point>
   <point>Maximální pevná šíøka okna byla z 1000 pixelù navıšena na 10000 pixelù.</point>
   <point>Soubory s grafy lze nyní èíst a kopírovat za bìhu Wixu.</point>
  </update>
  
  <update>
   <date>17.1.2011</date>
   <version>1.7.0.1</version>
   <point>V oknì "O programu" pøibyla informace, zda se jedná o free verzi.</point>
   <point>V plné verzi Wixu je u moné skrıt reklamní panel a zároveò pouívat protokol modbus.</point>
   <point>Ve free verzi Wixu je reklamní panel zobrazen trvale.</point>
  </update>

  <update>
   <date>3.1.2011</date>
   <version>1.7.0.0</version>
   <point>Rozdìlení programu na free verzi a plnou verzi.</point>
   <point>Rozšíøení dialogu pro nastavení akcí a podmínek.</point>
   <point>Podmínky lze spojovat operátory AND a OR.</point>
   <point>K jedné podmínce lze nastavit více akcí, které se mají vykonat pøi splnìní dané podmínky.</point>
  </update>
  
  <update>
   <date>11.10.2010</date>
   <version>1.6.6.0</version>
   <point>Pøidán modul DT4120.</point>
   <point>V dialogu "Nastavení pøipojení" pøibyla monost zvolení parity.</point>   
  </update>
  
  <update>
   <date>30.8.2010</date>
   <version>1.6.5.0</version>
   <point>Pøidán do Wixu webovı server.</point>
  </update>
 
  <update>
   <date>12.8.2010</date>
   <version>1.6.4.0 update</version>
   <point>Pøidán modul TDS s moností zobrazení ètyø vstupù.</point>
   <point>Pøidán modul TME Multi.</point>
  </update>
  
  <update>
   <date>7.7.2010</date>
   <version>1.6.3.2 update</version>
   <point>Pøidána monost ukládat namìøené velièiny v hexadecimálním formátu.</point>
  </update>

  <update>
   <date>1.6.2010</date>
   <version>1.6.3.1</version>
   <point>Pøidáno zaøízení Drak4.</point>
   <point>Odstranìní chyby rozsahu poèáteèní adresy u Modbus zaøízení.</point>
  </update>

  <update>
   <date>22.3.2010</date>
   <version>1.6.3.0</version>
   <point>Se zaøízením TH2E a AD4 lze nyní komunikovat i pøes XML (zaízení musí bıt nastavené ve webovém reimu).</point>
  </update>

  <update>
   <date>15.3.2010</date>
   <version>1.6.2.3</version>
   <point>Odstranìní chyby rozsahu poèáteèní adresy u Modbus zaøízení.</point>
  </update>

  <update>
   <date>11.3.2010</date>
   <version>1.6.2.2</version>
   <point>Odstranìní chyby nastavení èítaèe Quida.</point>
  </update>

  <update>
   <date>1.3.2010</date>
   <version>1.6.2.1</version>
   <point>Pøibyla akce typu spustit dávkovı soubor.</point>
   <point>Pøibyla akce typu nahrát data na web (HTTP GET).</point>
   <point>Panely vıstupu Quida novì obsahují tlaèítka pro ovládání vıstupù.</point>
  </update>

  <update>
   <date>14.1.2010</date>
   <version>1.6.1.0</version>
   <point>Pøibyla monost zobrazovat hodnotu jako barevnı sloupec (bargraf).</point>
   <point>Pøibyly nápovìdy v záhlaví kadého okna.</point>
   <point>Panel "Nastavení" zmìnìn na panel s tlaèítky (nastavení, pøidat modul, pøidat graf, o aplikaci, minimalizovat a ukonèit).</point>
   <point>Pøi najetí myši na panel se zobrazí tool panel s tlaèítky nastavení a odstranit.</point>
  </update>

  <update>
   <date>1.10.2009</date>
   <version>1.6.0.0</version>
   <point>Pøidaná monost rozmístìní panılkù do více oken.</point>
   <point>V oknì zobrazující graf pøibyla funkce posouvat graf tahem myši.</point>
   <point>Pøidaná podpora modulu TH2E s logováním.</point>
  </update>

  <update>
   <date>2.9.2009</date>
   <version>1.5.0.2</version>
   <point>Opravena chyba se zamrznutím programu po spuštìní.</point>
  </update>

  <update>
   <date>13.8.2009</date>
   <version>1.5.0.1</version>
   <point>Opravena chyba se zapamatováním nastavení zástupného textu pøi ukonèení programu.</point>
  </update>

  <update>
   <date>23.7.2009</date>
   <version>1.5.0.0</version>
   <point>Pøidaná podpora protokolu Modbus RTU</point>
   <point>Pøidán reklamní panel "Papouch"</point>
  </update>

  <update>
   <date>8.7.2009</date>
   <version>1.4.4.0</version>
   <point>U grafù pøidaná monost zobrazení velièin z historie.</point>
   <point>Pøidaná monost zvolit zástupnı text pro rozsah hodnot.</point>
  </update>

  <update>
   <date>29.5.2009</date>
   <version>1.4.3.3</version>
   <point>Pøidaná monost vypnout autorizaci u SMTP Serveru.</point>
   <point>Pøeuspoøádání poloek v popupmenu.</point>
  </update>

  <update>
   <date>20.3.2009</date>
   <version>1.4.3.0</version>
   <point>V akcích pøidána monost poslat emailem a sms teplotu èidla.</point>
   <point>V akcích pøidána monost sepnutí Quida na urèitou dobu.</point>
  </update>

  <update>
   <date>27.2.2009</date>
   <version>1.4.2.0</version>
   <point>Pøidán modul THE.</point>
  </update>

  <update>
   <date>26.2.2009</date>
   <version>1.4.1.0</version>
   <point>Pøidán modul THT.</point>
  </update>

  <update>
   <date>13.2.2009</date>
   <version>1.4.0.9</version>
   <point>Pøidán modul Anemometr.</point>
  </update>

  <update>
   <date>5.1.2009</date>
   <version>1.4.0.8</version>
   <point>Opravená chyba v TCP komunikaci.</point>
  </update>

  <update>
   <date>24.11.2008</date>
   <version>1.4.0.7</version>
   <point>Opravená chyba v obnovování TCP spojení.</point>
  </update>

  <update>
   <date>10.11.2008</date>
   <version>1.4.0.6</version>
   <point>Opravena chyba pøi posílání SMS zpráv.</point>
   <point>Pøi generování barev grafu odfiltrovány tmavé barvy.</point>
  </update>

  <update>
   <date>10.10.2008</date>
   <version>1.4.0.4</version>
   <point>Pøidaná monost vynulování èítaèù u modulu Quido</point>
   <point>Opravena chyba v ukládání dat.</point>
  </update>

  <update>
   <date>5.9.2008</date>
   <version>1.4.0.3</version>
   <point>Opravena chyba mìøení u teplmìru na Quidu.</point>
   <point>U automatického skrıvání byla pøidána prodleva mezi najetím myši na tray iconu a zobrazením okna.</point>
  </update>

  <update>
   <date>20.8.2008</date>
   <version>1.4.0.2</version>
   <point>Pøidaná zpìtná kompatibilita k modulùm TQS3 s firmwarem v.3.1.</point>
  </update>

  <update>
   <date>6.8.2008</date>
   <version>1.4.0.1</version>
   <point>Odstranìní chyby pøi pøidání senzoru z popupmenu.</point>
  </update>

  <update>
   <date>30.7.2008</date>
   <version>1.4.0.0</version>
   <point>Pøidána monost zaslání emailu nebo SMS pøi pøekroèení hodnoty.</point>
  </update>

  <update>
   <date>31.3.2008</date>
   <version>1.3.4.2</version>
   <point>Monost zobrazení grafù v samostatném oknì.</point>
   <point>Pøidáno tlaèítko nastavení.</point>
  </update>

  <update>
   <date>3.3.2008</date>
   <version>1.3.4.0</version>
   <point>Nastavení pøepoètù pro kadé èidlo zvláš.</point>
  </update>

  <update>
   <date>11.2.2008</date>
   <version>1.3.3.1</version>
   <point>Opravená chyba v obnovování TCP spojení.</point>
  </update>

  <update>
   <date>5.2.2008</date>
   <version>1.3.3.0</version>
   <point>Wix novì umí i starší teplomìry TQS1</point>
   <point>Monost synchronizace ukládání dat v urèitı èas</point>
   <point>Opravena chyba v konverzi ze °C do F</point>
  </update>

  <update>
   <date>23.11.2007</date>
   <version>1.3.2.2</version>
   <point>Do Wixu je integrován vlhkomìr THY</point>
  </update>

  <update>
   <date>2.11.2007</date>
   <version>1.3.2.1</version>
   <point>U jednotek pøibyla monost nastavení poètu desetinnıch míst</point>
  </update>

  <update>
   <date>10.10.2007</date>
   <version>1.3.2.0</version>
   <point>Podpora I/O modulù Quido (pouze vstupy)</point>
  </update>

  <update>
   <date>25.9.2007</date>
   <version>1.3.1.0</version>
   <point>Náhledové grafy</point>
  </update>

  <update>
    <date>18.7.2007</date>
    <version>1.3.0.0</version>
    <point>Pøidány mìøící pøevodníky AD4RS, AD4ETH (TCP/IP), AD4USB</point>
    <point>Monost nastavení jednotek a jejich pøepoètù</point>
    <point>Monost volby zpùsobu získání namìøené hodnoty z TME</point>
  </update>

  <update>
    <date>9.7.2007</date>
    <version>1.2.4.0</version>
    <point>Podpora pøipojení TMU pøes Virtual port</point>
  </update>


  <update>
    <date>3.5.2007</date>
    <version>1.2.3.0</version>
    <point>Vylepšeno nastavení ukládání</point>
  </update>

  <update>
    <date>19.04.2007</date>
    <version>1.2.2.1</version>
    <point>Monost zadat adresu TME jako URL a ne jen jako IP adresu</point>
    <point>Omezení názvu èidla na unikátní a neprázdnı</point>
  </update>

  <update>
    <date>3.4.2007</date>
    <version>1.2.2.0</version>
    <point>Pøidaná funkce proklikávání okna (okno je sice zobrazeno, ale je neaktivní na kliknutí - je tedy moné ovládat myší okno pod ním)</point>
    <point>Odstranìní typu dotazu "Normal" u TME</point>
  </update>

  <update>
    <date>13.3.2007</date>
    <version>1.2.1.0</version>
    <point>Podpora teplomìrù TQS3</point>
    <point>Rozdìlení èidel podle typu</point>
    <point>Monost nastavení intervalu mìøení a zápisu</point>
    <point>Pøidání typu dotazu "XML-File" u TME</point>
  </update>

  <update>
    <date>12.2.2007</date>
    <version>1.0.2.1</version>
    <point>Zpøehlednìní formuláøe "obecného nastavení"</point>
    <point>Upravení poèáteèní pozice okna</point>
  </update>

  <update>
    <date>7.2.2007</date>
    <version>1.0.2.0</version>
    <point>Úprava rozvrení formuláøe "obecného nastavení"</point>
    <point>V obecném nastavení pøidán list èidel</point>
    <point>Pøidána volba "Pøidat" v menu dostupném po kliknutí pravım tlaèítkem na ikonu Wixu v trayi</point>
  </update>

  <update>
    <date>6.2.2007</date>
    <version>1.0.1.0</version>
    <point>Pøidaná funkce automatického rozpoznávání zda aplikace neni mimo monitor (napøíklad pøi zmìnì monitoru nebo sníení rozlišení)</point>
  </update>

</project>